### ISSUE TITLE
Error when running gulp build

### ISSUE THREAD

**Issue by duffbuster** [FountainJS/generator-fountain-angular2#42]
I'm getting an error when running gulp build:
`[09:19:40] 'inject' errored after 33 ms
[09:19:40] Error: Error: @angular/core is not installed. Try running `bower install`.
    at /Users/35516/Freelance/webapp-test/node_modules/wiredep/wiredep.js:30:56
    at /Users/35516/Freelance/webapp-test/node_modules/wiredep/lib/detect-dependencies.js:145:29
    at forOwn (/Users/35516/Freelance/webapp-test/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/Users/35516/Freelance/webapp-test/node_modules/wiredep/node_modules/lodash/dist/lodash.js:3303:9)
    at detectDependencies (/Users/35516/Freelance/webapp-test/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/Users/35516/Freelance/webapp-test/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/Users/35516/Freelance/webapp-test/node_modules/wiredep/wiredep.js:135:34)
    at DestroyableTransform.Transform._read (/Users/35516/Freelance/webapp-test/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/35516/Freelance/webapp-test/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/35516/Freelance/webapp-test/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/35516/Freelance/webapp-test/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/35516/Freelance/webapp-test/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at queueData (/Users/35516/Freelance/webapp-test/node_modules/map-stream/index.js:43:21)`

I saw that it said "Try running bower install", but after running that, the same thing happened. Did I do something wrong?

**Comment by Swiip** [comment]
Which options did you chose? I see references of Wiredep and Angular 2 which is strange because we have blocked this particular association as there was no Angular 2 bower release.

**Comment by zckrs** [comment]
Do you run `yo fountain-webapp` or `yo fountain-angular2` ?

**Comment by duffbuster** [comment]
I ran `yo fountain-angular2`, and chose "None with Bower and script injection", TypeScript, and CSS

**Comment by zckrs** [comment]
Issue from https://github.com/FountainJS/fountain-generator/blob/master/lib/Base.js#L41 we don't have responses.framework when fountain-angular2 is directly used

**Comment by zckrs** [comment]
0.5.3 released
