### ISSUE TITLE
Issue running gulp

### ISSUE THREAD

**Issue by hugobluefuse** [FountainJS/generator-fountain-angular2#88]
## Description

Installing and running the generator worked fine. But when running gulp, an error message is shown. See below:

### Error Message & Stack Trace
[15:10:51] Loading C:\projects\web\laravel\angular\gulp_tasks\browsersync.js
[15:10:51] Loading C:\projects\web\laravel\angular\gulp_tasks\karma.js
[15:10:51] Loading C:\projects\web\laravel\angular\gulp_tasks\misc.js
[15:10:51] Loading C:\projects\web\laravel\angular\gulp_tasks\webpack.js
[15:10:52] Using gulpfile C:\projects\web\laravel\angular\gulpfile.js
C:\Users\Hugo\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\Hugo\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

### Specs
Windows 10
NPM 3.10.8
Node 6.6.0

Is it me?

**Comment by hugobluefuse** [comment]
My bad.

I'll close the ticket down. Thanks for the help

**Comment by zckrs** [comment]
Np :smiley:
