### ISSUE TITLE
Getting console error and application not working

### ISSUE THREAD

**Issue by rkori215** [FountainJS/generator-fountain-angular2#96]
After installing generator and run npm run serve getting the below error in console.

Uncaught (in promise) Error: (SystemJS) Unexpected token <(…)

and application not showing anything in browser.

and am using angular2, typescript, systemjs, jspm

**Comment by Swiip** [comment]
Can you dig a bit deeper? Have you localized the file causing the problem? Can you paste your full .yo-rc and environment? Our tests are passing...

**Comment by rkori215** [comment]
my .yo-rc json is below..
{
  "generator-fountain-angular2": {
    "version": "1.0.0-rc1",
    "props": {
      "framework": "angular2",
      "modules": "systemjs",
      "js": "typescript",
      "ci": [],
      "css": "scss",
      "resolved": "/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular2/generators/app/index.js",
      "namespace": "fountain-angular2",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "sample": "techs",
      "router": "uirouter"
    }
  }
}


and now am getting below error in terminal

Unhandled rejection Error: Uncaught, unspecified "error" event. ([object Object])
    at Gulp.emit (events.js:144:17)
    at Gulp.src.emit (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/gulp-hub/node_modules/fwd/index.js:31:10)
    at Object.error (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/gulp/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/lib/mapSeries.js:43:14)
    at f (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/node_modules/once/once.js:25:25)
    at f (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/node_modules/once/once.js:25:25)
    at done (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:24:15)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rakeshkoripella/Desktop/angular2_Project/resRECV1/node_modules/jspm/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

[15:48:36] The following tasks did not complete: default, build, <parallel>, systemjs
[15:48:36] Did you forget to signal async completion?
