### ISSUE TITLE
Build error on systemjs (windows)

### ISSUE THREAD

**Issue by will421** [FountainJS/generator-fountain-angular2#98]
## Description
This issue occur just after project generation when running "gulp".

I found this issue https://github.com/systemjs/builder/issues/621, that lead to this one : https://github.com/systemjs/systemjs/issues/1317.
It say that there is a fix 0.19.37 of systemjs.
What I had is "systemjs@0.19.36" dependency of "jspm@0.17.0-beta.25".
I changed jspm version in package.json to 0.17.0-beta.32 that depend on "systemjs@0.19.41"
But below issue still occur.

Found also this https://github.com/mgechev/angular-seed/issues/1227#issuecomment-248425132, but I do not know how to use it.

### Error Message & Stack Trace

```
D:\Angular_2_test\yeoman>gulp
[09:35:06] Loading D:\Angular_2_test\yeoman\gulp_tasks\browsersync.js
[09:35:06] Loading D:\Angular_2_test\yeoman\gulp_tasks\build.js
[09:35:11] Loading D:\Angular_2_test\yeoman\gulp_tasks\karma.js
[09:35:14] Loading D:\Angular_2_test\yeoman\gulp_tasks\misc.js
[09:35:14] Loading D:\Angular_2_test\yeoman\gulp_tasks\scripts.js
[09:35:15] Loading D:\Angular_2_test\yeoman\gulp_tasks\styles.js
[09:35:15] Loading D:\Angular_2_test\yeoman\gulp_tasks\systemjs.js
[09:35:17] Using gulpfile D:\Angular_2_test\yeoman\gulpfile.js
[09:35:17] Starting 'default'...
[09:35:17] Starting 'clean'...
[09:35:17] Finished 'clean' after 57 ms
[09:35:17] Starting 'build'...
[09:35:17] Starting 'systemjs'...
[09:35:17] Starting 'systemjs:html'...
[09:35:17] Starting 'styles'...
[09:35:17] Starting 'other'...
[09:35:17] Starting 'replaceTemplates'...
[09:35:18] Finished 'other' after 110 ms
[09:35:18] Finished 'systemjs:html' after 788 ms
[09:35:18] Finished 'styles' after 791 ms
[09:35:18] Finished 'replaceTemplates' after 804 ms
[09:35:18] Starting 'systemjs'...
[09:35:21] 'systemjs' errored after 2.96 s
[09:35:21] Error on fetch for .tmp\templates\index.ts at file:///D:/Angular_2_test/yeoman/.tmp\templates\index.ts
        Error: ENOENT: no such file or directory, open 'D:\Angular_2_test\yeoman\.tmp\templates\index.ts'
    at Error (native)
Unhandled rejection Error: Uncaught, unspecified "error" event. ([object Object])
    at Gulp.emit (events.js:163:17)
    at Gulp.src.emit (D:\Angular_2_test\yeoman\node_modules\fwd\index.js:31:10)
    at Object.error (D:\Angular_2_test\yeoman\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (D:\Angular_2_test\yeoman\node_modules\now-and-later\lib\mapSeries.js:43:14)
    at f (D:\Angular_2_test\yeoman\node_modules\once\once.js:25:25)
    at f (D:\Angular_2_test\yeoman\node_modules\once\once.js:25:25)
    at done (D:\Angular_2_test\yeoman\node_modules\async-done\index.js:24:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (D:\Angular_2_test\yeoman\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Angular_2_test\yeoman\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\Angular_2_test\yeoman\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\Angular_2_test\yeoman\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\Angular_2_test\yeoman\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (D:\Angular_2_test\yeoman\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\Angular_2_test\yeoman\node_modules\bluebird\js\release\async.js:148:10)

[09:35:21] The following tasks did not complete: default, build, <parallel>, systemjs
[09:35:21] Did you forget to signal async completion?
```

### Config

```json
{
  "generator-fountain-angular2": {
    "version": "1.0.0-rc1",
    "props": {
      "resolved": "C:\\Users\\WB\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-angular2\\generators\\app\\index.js",
      "namespace": "fountain-angular2:app",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "framework": "angular2",
      "modules": "systemjs",
      "css": "scss",
      "js": "typescript",
      "ci": [],
      "sample": "hello",
      "router": "router"
    }
  }
}
```

## Environment

```
>node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v6.9.1
win32 10.0.10586

>yo --version
1.8.5

>npm --version
4.0.3
```

**Comment by sahilshaikh89** [comment]
facing the same issue.

**Comment by Kamen84** [comment]
+1 same issue

**Comment by mbennett** [comment]
Same issue here.
```
>node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v6.9.1
win32 6.1.7601

>yo --version
1.8.5

>npm --version
4.0.5
```

**Comment by will421** [comment]
Here is a patch for generated projects based on @Swiip pull request. Thanks to him
[fix_systemjs_build.zip](https://github.com/FountainJS/generator-fountain-angular2/files/693112/fix_systemjs_build.zip)
